title = "Mai Linh Nguyen"
baseURL = "https://nguyenmailinh.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  github = "https://github.com/MaiLinhGroup"
  linkedin = "https://www.linkedin.com/in/mailinhng/"
  twitter = "https://twitter.com/mailinhgonguyen"
  instagram = "https://www.instagram.com/mle_ng/?hl=ur"
  background_color_class = "bg-black"
  recent_posts_number = 3